### ISSUE TITLE
[Enhancement] Add Configuration for TOC helper to control header levels

### ISSUE THREAD

**Issue by BradleyGoulding** [estruyf/doctor#153]
**Is your feature request related to a problem? Please describe.**
The TOC shortcode plugin assumes a default configuration of 4 header levels. 

**Describe the solution you'd like**
I would like a basic configuration option to set which header levels to apply to the TOC

**Describe alternatives you've considered**
Rework documentation to limit what headers are used, however this is less than ideal when using sub headings for clarity but not navigation

**Additional context**
Screenshot showing content with only h2 in the TOC
<img width="1324" alt="Screenshot 2023-12-03 at 19 21 29" src="https://github.com/estruyf/doctor/assets/4862180/3c66e778-7651-4acc-9e6c-d65c3965a0d0">

**Comment by estruyf** [comment]
Your change has been included in version `1.12.0` and got released.
