### ISSUE TITLE
Support Admonitions

### ISSUE THREAD

**Issue by P3N-101** [estruyf/doctor#53]
If you get HTML working, then supporting admonitions would be really cool.  Its a feature I have used a lot! 

Like [Remark Admonitions](https://github.com/elviswolcott/remark-admonitions)

**Comment by estruyf** [comment]
@P3N-101 this is indeed the plan. I will work on shortcode support. Which could have admonitions support as well.

**Comment by estruyf** [comment]
Now supported in version `1.7.0`
