### ISSUE TITLE
[Enhancement] Customize destination folders in SharePoint

### ISSUE THREAD

**Issue by gustavocovas** [estruyf/doctor#61]
**Is your feature request related to a problem? Please describe.**
I want to use Doctor for a specific project within a SharePoint site that is already manually maintained. E.g.: I want to deploy the pages to a specific folder (`mycompany.sharepoint.com/sites/mydepartment/myproject/`) instead of the default `sitepages/`.

**Describe the solution you'd like**
Allow custom deploy folders.

**Describe alternatives you've considered**
I known that I can define folders at each file slug, but they are created under `sitepages` anyway. Reading the docs and the source code, it appears that Doctor is intended to use with a clean / fresh SharePoint site. Is this correct? For my use case, I think using a subsite could work. 

**Additional context**

**Comment by estruyf** [comment]
Thanks @gustavocovas for this issue. Do I understand you correctly you want to be able to create pages in another `pages library`? If that is the case, this is not supported I believe. There can only be one modern pages library.

The tool is not intended to only work on clean/fresh sites. You can use it on existing sites as well. The tool itself will not remove content, or you need to specify it explicitly to do that.

**Comment by gustavocovas** [comment]
Thank you, @estruyf! I was not understanding some concepts correctly. After your explanation and some research, I realized my feature request does not make much sense.
