### ISSUE TITLE
[BUG] allowHtml interferes with code highlighting

### ISSUE THREAD

**Issue by robert-lindstrom** [estruyf/doctor#72]
**Describe the bug**
Some characters are erroneously html-encoded in code highlight section when allowHtml is set to true.

**To Reproduce**
If allowHtml is set to true and the markdown contains the following code highlight:

<pre>
```javascript
console.log('test');
```
</pre>

the output is:

<pre>
console.log(&amp;apos;test&amp;apos;);
</pre>

**Expected behavior**
The output should be:

<pre>
console.log('test');
</pre>

**Additional context**
We tested this with doctor 1.7.0 and 1.8.0-beta.6217071

**Comment by estruyf** [comment]
Thanks, found what was causing the issue. Fix and extra tests have been added. Once the next build has been completed. It will be available in `beta`.

**Comment by estruyf** [comment]
This has been released in v1.8.0
