### ISSUE TITLE
[BUG] Multilingual environment not supported

### ISSUE THREAD

**Issue by WilbertWalrus** [estruyf/doctor#78]
````
$ doctor publish

DOCTOR v1.8.0

START:  publish job

Warning:  You specified to allow custom HTML usage in Doctor. Be aware that once you modify the page on SharePoint itself, the HTML will be overwritten. Best is to maintain content from the Doctor sources.

  √ Authenticate to M365 with password
  √ Fetch all markdown files
  \ Process markdown files
    Updating navigation
    Change the look of the site
(node:72872) UnhandledPromiseRejectionWarning: Error: Command failed: localm365 spo listitem list --webUrl "https://redacted.sharepoint.com/sites/hrdept" --title "Site Pages" --fields "ID,Title,FileRef" -o json
Error: Request failed with status code 404
````

Then ran the failed command directly with `--debug`:

> localm365 spo listitem list --webUrl "https://redacted.sharepoint.com/sites/hrdept" --title "Site Pages" --fields "ID,Title,FileRef" -o json --debug

And error came back with:

> List 'Site Pages' does not exist at site with URL 'https://redacted.sharepoint.com/sites/hrdept'

Looked around and came across these helpful links: 
https://teddit.net/r/sharepoint/comments/k8djlk/list_site_pages_does_not_exist_at_site_with_url/
https://kenneho.net/2020/12/16/sharepoint-list-site-pages-does-not-exist-at-site/

Changed "Site Pages" title to its original language would then work. So looks like this is a multilingual environment issue as we had setup our ScarePoint site originally in a different language, then changed it to English, so "Site Pages" does not actually and we need to get the "Site Pages" name in its original language. 😭

Any support or workaround for this?

**Comment by estruyf** [comment]
@WilbertWalrus thanks! I Will work on the fix for this.

**Comment by estruyf** [comment]
Version `1.8.1` has been published. This should fix the issue. Thanks again for reporting this.
